<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DEV-LPT331" failures="3" tests="8" name="HRM application Test cases" time="28.183" errors="0" timestamp="2024-01-26T14:22:02 IST">
  <testcase classname="com.hrm.qa.tests.DashBoardPageTest" name="@BeforeMethod seUp" time="5.206">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.hrm.qa.pages.LoginPage.validateLogin(LoginPage.java:50)
at com.hrm.qa.tests.DashBoardPageTest.seUp(DashBoardPageTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod seUp -->
  <testcase classname="com.hrm.qa.tests.DashBoardPageTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="com.hrm.qa.tests.DashBoardPageTest" name="@BeforeMethod seUp" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod seUp -->
  <testcase classname="com.hrm.qa.tests.DashBoardPageTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="com.hrm.qa.tests.DashBoardPageTest" name="@BeforeMethod seUp" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod seUp -->
  <testcase classname="com.hrm.qa.tests.DashBoardPageTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="com.hrm.qa.tests.LoginPageTest" name="loginTestDataProvider" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.NullPointerException">
      <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: java.lang.NullPointerException
at org.apache.poi.poifs.filesystem.FileMagic.prepareToCheckMagic(FileMagic.java:222)
at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:214)
at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:185)
at com.hrm.qa.util.TestUtil.getTestData(TestUtil.java:39)
at com.hrm.qa.tests.LoginPageTest.getLoginData(LoginPageTest.java:52)
... 25 more
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- loginTestDataProvider -->
  <testcase classname="com.hrm.qa.tests.LoginPageTest" name="loginPageTitleTest" time="0.016"/>
  <testcase classname="com.hrm.qa.tests.LoginPageTest" name="loginpageNameTest" time="0.506"/>
  <testcase classname="com.hrm.qa.tests.LoginPageTest" name="loginTest" time="1.686">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.hrm.qa.pages.LoginPage.validateLogin(LoginPage.java:50)
at com.hrm.qa.tests.LoginPageTest.loginTest(LoginPageTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.hrm.qa.tests.LoginPageTest" name="loginErrorMessageTest" time="0.758">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.hrm.qa.pages.LoginPage.validateLogin(LoginPage.java:50)
at com.hrm.qa.tests.LoginPageTest.loginErrorMessageTest(LoginPageTest.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorMessageTest -->
  <testcase classname="com.hrm.qa.tests.DashBoardPageTest" name="verifyAssignLeaveButtonTest" time="0.0">
    <skipped/>
  </testcase> <!-- verifyAssignLeaveButtonTest -->
  <testcase classname="com.hrm.qa.tests.DashBoardPageTest" name="verifyDashboardLabelTest" time="0.0">
    <skipped/>
  </testcase> <!-- verifyDashboardLabelTest -->
  <testcase classname="com.hrm.qa.tests.DashBoardPageTest" name="verifyDashboardPageTitleTest" time="0.0">
    <skipped/>
  </testcase> <!-- verifyDashboardPageTitleTest -->
</testsuite> <!-- HRM application Test cases -->
